# Generated by Django 5.0.4 on 2024-05-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cep", models.CharField(max_length=10)),
                ("type", models.CharField(max_length=25)),
                ("name", models.CharField(max_length=100)),
                ("number", models.IntegerField()),
                ("state", models.CharField(max_length=2)),
                ("district", models.CharField(max_length=100)),
                ("latitude", models.CharField(max_length=25)),
                ("longitude", models.CharField(max_length=25)),
            ],
        ),
    ]
