# Generated by Django 5.0.4 on 2024-06-04 05:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="city",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
