# Generated by Django 5.0.4 on 2024-06-04 05:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_address_city"),
    ]

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("icon", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
