# Generated by Django 5.0.4 on 2024-06-04 05:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0003_user_description"),
        ("common", "0003_products"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="products",
            field=models.ManyToManyField(blank=True, null=True, to="common.products"),
        ),
    ]
