# Generated by Django 5.0.4 on 2024-06-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0005_user_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="img",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="garagem/"
            ),
        ),
    ]
