# Generated by Django 5.1.2 on 2024-11-02 04:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0006_alter_user_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="img",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="images/"
            ),
        ),
    ]
